# Generated by Django 5.2.3 on 2025-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_paper', models.CharField(max_length=50, verbose_name='لون الورق')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='حجم الورق')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=100, verbose_name='نوع الورق')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='حالة الطلب')),
            ],
        ),
    ]
