# Generated by Django 5.2.3 on 2025-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=100, verbose_name='نوع الورق')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
            ],
        ),
    ]
