# Generated by Django 5.2.3 on 2025-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_papertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='حجم الورق')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
            ],
        ),
    ]
