# Generated by Django 5.2.3 on 2025-10-04 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('file_name', models.FileField(upload_to='uploads/', verbose_name='الملف')),
                ('printing_sides', models.CharField(choices=[('one side', 'وجه واحد'), ('tow side', 'وجهين')], default='one side', max_length=20, verbose_name='الطباعة على وجه /وجهين')),
                ('number_of_sheets', models.PositiveIntegerField(verbose_name='عدد الاوراق')),
                ('quantity', models.PositiveIntegerField(verbose_name='عدد النسخ')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('paper_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papersize', verbose_name='حجم الورق')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papertype', verbose_name='نوع الورق')),
                ('printing_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papercolor', verbose_name='لون الطباعة')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.status', verbose_name='الحالة')),
            ],
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='orders.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
