# Generated by Django 5.2.3 on 2025-09-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('file_name', models.CharField(max_length=200, verbose_name='اسم الملف')),
                ('paper_type', models.CharField(choices=[('plain paper', 'عادي'), ('glossy paper', 'لمع'), ('sticky paper', 'لاصق'), ('cardboard', 'مقوى')], default='plain paper', max_length=50, verbose_name='نوع الورق')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], default='A4', max_length=50, verbose_name='حجم الورق')),
                ('printing_color', models.CharField(choices=[('black and white', 'ابيض واسود'), ('colored', 'الوان')], default='black and white', max_length=20, verbose_name='لون الطباعة')),
                ('printing_sides', models.CharField(choices=[('one side', 'وجه واحد'), ('tow side', 'وجهين')], default='one side', max_length=20, verbose_name='الطباعة على وجه /وجهين')),
                ('quantity', models.PositiveIntegerField(verbose_name='عدد النسخ')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('inprogress', 'جاري التنفيذ'), ('done', 'تم التنفيذ')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
        ),
    ]
