# Generated by Django 5.2.3 on 2025-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='file_name',
            field=models.FileField(upload_to='uploads/', verbose_name='الملف'),
        ),
    ]
