# Generated by Django 5.2.3 on 2025-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes_alter_order_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_sheets',
            field=models.PositiveIntegerField(default=11, verbose_name='عدد الاوراق'),
            preserve_default=False,
        ),
    ]
