# Generated by Django 5.2.3 on 2025-09-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_papersize'),
        ('orders', '0003_order_number_of_sheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paper_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papersize', verbose_name='حجم الورق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papertype', verbose_name='نوع الورق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='printing_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.papercolor', verbose_name='لون الطباعة'),
        ),
    ]
